spring:
  application:
    name: vr
  thymeleaf:
        prefix: classpath:/static/
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      name: test
      #driver-class-name: net.sf.log4jdbc.DriverSpy
      #url: jdbc:log4jdbc:mysql://localhost:3306/ck?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      url: jdbc:mysql://108.61.223.188:3306/ck?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: wang9403
  redis:
    host: 108.61.223.188
    port: 6379
    password: 