spring:
  application:
    name: vr
  thymeleaf:
        prefix: classpath:/static/
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: net.sf.log4jdbc.DriverSpy
      name: test
      url: jdbc:log4jdbc:mysql://localhost:3306/ck?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: wang9403
